const express=require('express')
const userSignUpController = require('../controller/userSignUp')
const userSignInController = require('../controller/userSignIn')
const authToken = require('../middleware/authToken')
const userDetails = require('../controller/userDetails')
const userLogout = require('../controller/userLogout')
const allUsers = require('../controller/allUsers')
const updateUser = require('../controller/updateRole')
const uploadProduct = require('../controller/uploadProduct')
const getProducts = require('../controller/getProducts')
const router = express.Router()
router.post('/signup', userSignUpController)
router.post('/signin', userSignInController)
router.get('/user-details', authToken,userDetails)
router.get('/userLogout', userLogout)
router.get('/all-users', authToken,allUsers)
router.post('/update-user', authToken,updateUser)
router.post('/upload-product', authToken,uploadProduct)
router.get('/get-products',getProducts)
module.exports = router
