const express=require('express')
const userSignUpController = require('../controller/userSignUp')
const userSignInController = require('../controller/userSignIn')
const authToken = require('../middleware/authToken')
const userDetails = require('../controller/userDetails')
const userLogout = require('../controller/userLogout')
const allUsers = require('../controller/allUsers')
const updateUser = require('../controller/updateRole')
const uploadProduct = require('../controller/uploadProduct')
const getProducts = require('../controller/getProducts')
const updateProduct = require('../controller/updateProduct')
const getproductByCategory = require('../controller/productByCategory')
const CategoryWiseProduct = require('../controller/categoryWiseProduct')
const fetchProduct = require('../controller/fetchProduct')
const addProductToCart = require('../controller/addProductToCart')
const countCartProducts = require('../controller/countCartProducts')
const cartProducts = require('../controller/cartProducts')
const increaseQuantity = require('../controller/increaseQuantityOfProductCart')
const deleteCartProduct = require('../controller/deleteCartProduct')
const searchProducts = require('../controller/searchProducts')
const FilterProducts = require('../controller/FilterProducts')
const router = express.Router()
//user Apis
router.post('/signup', userSignUpController)
router.post('/signin', userSignInController)
router.get('/user-details', authToken,userDetails)
router.get('/userLogout', userLogout)
router.get('/all-users', authToken,allUsers)
router.post('/update-user', authToken,updateUser)
//Product Apis
router.post('/upload-product', authToken,uploadProduct)
router.get('/get-products',getProducts)
router.post('/update-product',authToken,updateProduct)
router.get('/get-productCategory',getproductByCategory)
router.post('/categoryWiseProducts',CategoryWiseProduct) 
router.post('/product',fetchProduct) 
router.get('/search',searchProducts) 
router.post('/filter-products',FilterProducts) 

// Cart Apis
router.post('/addToCart',authToken,addProductToCart)
router.get('/countProducts',authToken,countCartProducts) 
router.get('/all-cart-products',authToken,cartProducts)
router.post('/increaseQuantity',authToken,increaseQuantity) 
router.post('/deleteProduct',authToken,deleteCartProduct) 

module.exports = router
